import { useState, useCallback, useMemo, useEffect, useRef } from "react";
import "./ParameterBlock.scss";
import PropTypes from "prop-types";

const PARAMETERS_UPDATED_EVENT = "parametersUpdated";
const normalizeValue = (value) => {
  if (value === null || value === undefined) {
    return "";
  }
  return typeof value === "string" ? value : String(value);
};

const buildDragPayload = (param) => ({
  label: param.label,
  value: param.value,
  family: param.family || "variable",
  id: param.id,
  source: param.source || "user",
  isDataParameter: Boolean(param.isDataParameter),
  isAutoGenerated: Boolean(param.isAutoGenerated),
});

export default function ParameterBlock({
  parameters,
  setParameters,
  onShowModal,
  onShowDeleteModal,
}) {
  // State to track which parameter and field is being edited
  const [editingIndex, setEditingIndex] = useState(null);
  const [editingField, setEditingField] = useState(null);
  const [tempValue, setTempValue] = useState("");
  const [dropdownState, setDropdownState] = useState(false);
  const [searchTerm, setSearchTerm] = useState("");
  const [collapsedGroups, setCollapsedGroups] = useState({});

  // Drag state management
  const [isDragging, setIsDragging] = useState(false);
  const [dragOffset, setDragOffset] = useState(0);
  const [currentX, setCurrentX] = useState(0);
  const [canvasBounds, setCanvasBounds] = useState({ left: 0, right: 0 });
  const [dragStartPos, setDragStartPos] = useState({ x: 0, y: 0 });
  const [hasDragged, setHasDragged] = useState(false);
  const parameterBlockRef = useRef(null);

  const classifyParameter = useCallback((param) => {
    if (param.isDataParameter) {
      return { type: "data", color: "purple", icon: "◆" };
    }

    const label = normalizeValue(param.label).toLowerCase();
    const source = normalizeValue(param.source).toLowerCase();
    const isSystem = source === "system";

    if (
      isSystem ||
      label.includes("close") ||
      label.includes("close price") ||
      label.includes("live")
    ) {
      return { type: "manual", color: "green", icon: "●" };
    }

    if (isSystem || label.includes("indicator") || label.includes("output")) {
      return { type: "manual", color: "dark-blue", icon: "●" };
    }

    if (isSystem || label.includes("entry")) {
      return { type: "manual", color: "pink", icon: "●" };
    }

    return { type: "manual", color: "default", icon: "○" };
  }, []);

  const decoratedParameters = useMemo(() => {
    return parameters.map((param) => {
      const value = normalizeValue(param.value);
      const paramType = classifyParameter(param);
      return {
        ...param,
        value,
        paramType,
        isDataParameter: Boolean(param.isDataParameter),
        isAutoGenerated: Boolean(param.isAutoGenerated),
      };
    });
  }, [parameters, classifyParameter]);

  const groupedParameters = useMemo(() => {
    const groups = {
      data: [],
      manual: [],
    };

    decoratedParameters.forEach((param) => {
      const bucket = groups[param.paramType.type];
      if (bucket) {
        bucket.push(param);
      } else {
        groups.manual.push(param);
      }
    });

    return groups;
  }, [decoratedParameters]);

  const filteredGroupedParameters = useMemo(() => {
    if (searchTerm === "") {
      return groupedParameters;
    }

    const term = searchTerm.toLowerCase();
    const matches = (param) =>
      param.label.toLowerCase().includes(term) ||
      normalizeValue(param.value).toLowerCase().includes(term);

    return {
      data: groupedParameters.data.filter(matches),
      manual: groupedParameters.manual.filter(matches),
    };
  }, [groupedParameters, searchTerm]);

  const hasMatchingParameters =
    filteredGroupedParameters.data.length > 0 ||
    filteredGroupedParameters.manual.length > 0;

  const startEditing = useCallback(
    (index, field, currentValue) => {
      const target = parameters[index];
      if (!target) {
        return;
      }
      if (target.isAutoGenerated) {
        return;
      }
      if (target?.isDataParameter && field !== "value") {
        return;
      }
      setEditingIndex(index);
      setEditingField(field);
      setTempValue(currentValue);
    },
    [parameters]
  );

  const saveEdit = useCallback(() => {
    if (editingIndex !== null && editingField && tempValue.trim()) {
      const target = parameters[editingIndex];
      if (!target || target.isAutoGenerated) {
        setEditingIndex(null);
        setEditingField(null);
        setTempValue("");
        return;
      }
      if (target?.isDataParameter && editingField === "label") {
        setEditingIndex(null);
        setEditingField(null);
        setTempValue("");
        return;
      }
      setParameters((prev) =>
        prev.map((param, index) =>
          index === editingIndex
            ? { ...param, [editingField]: tempValue.trim() }
            : param
        )
      );
    }
    setEditingIndex(null);
    setEditingField(null);
    setTempValue("");
  }, [editingIndex, editingField, tempValue, parameters, setParameters]);

  const cancelEdit = useCallback(() => {
    setEditingIndex(null);
    setEditingField(null);
    setTempValue("");
  }, []);

  const handleKeyPress = useCallback(
    (e) => {
      if (e.key === "Enter") {
        saveEdit();
      } else if (e.key === "Escape") {
        cancelEdit();
      }
    },
    [saveEdit, cancelEdit]
  );

  const onClickDropdownButton = useCallback(() => {
    if (hasDragged) {
      return;
    }
    setDropdownState((prev) => !prev);
  }, [hasDragged]);

  const onClickToggleIcon = useCallback((e) => {
    e.stopPropagation();
    setDropdownState((prev) => !prev);
  }, []);

  // eslint-disable-next-line no-unused-vars
  const handleDeleteClick = useCallback(
    (index) => {
      const target = parameters[index];
      if (target?.isAutoGenerated) {
        return;
      }
      onShowDeleteModal(index);
    },
    [onShowDeleteModal, parameters]
  );

  const toggleGroup = useCallback((groupType) => {
    setCollapsedGroups((prev) => ({
      ...prev,
      [groupType]: !prev[groupType],
    }));
  }, []);

  useEffect(() => {
    const updateCanvasBounds = () => {
      if (parameterBlockRef.current) {
        const canvas = parameterBlockRef.current.closest(".react-flow");
        if (canvas) {
          const rect = canvas.getBoundingClientRect();
          const blockWidth = parameterBlockRef.current.offsetWidth;
          setCanvasBounds({
            left: 0,
            right: rect.width - blockWidth,
          });
        }
      }
    };

    updateCanvasBounds();
    window.addEventListener("resize", updateCanvasBounds);
    return () => window.removeEventListener("resize", updateCanvasBounds);
  }, []);

  const handleMouseDown = useCallback((e) => {
    if (
      e.target.closest(".dropdown-title") &&
      !e.target.closest(".toggle-icon")
    ) {
      setDragStartPos({ x: e.clientX, y: e.clientY });
      setHasDragged(false);
      const rect = parameterBlockRef.current.getBoundingClientRect();
      setDragOffset(e.clientX - rect.left);
    }
  }, []);

  const handleMouseMove = useCallback(
    (e) => {
      if (dragStartPos.x !== 0 && dragStartPos.y !== 0) {
        const deltaX = Math.abs(e.clientX - dragStartPos.x);
        const deltaY = Math.abs(e.clientY - dragStartPos.y);

        if (deltaX > 5 && deltaX > deltaY) {
          if (!isDragging) {
            setIsDragging(true);
            setHasDragged(true);
            document.body.style.cursor = "grabbing";
            document.body.style.userSelect = "none";
          }

          const newX = e.clientX - dragOffset;
          const constrainedX = Math.max(
            canvasBounds.left,
            Math.min(canvasBounds.right, newX)
          );
          setCurrentX(constrainedX);
        }
      }
    },
    [dragStartPos, dragOffset, canvasBounds, isDragging]
  );

  const handleMouseUp = useCallback(() => {
    if (isDragging) {
      setIsDragging(false);
      document.body.style.cursor = "";
      document.body.style.userSelect = "";
    }
    setDragStartPos({ x: 0, y: 0 });
  }, [isDragging]);

  useEffect(() => {
    document.addEventListener("mousemove", handleMouseMove);
    document.addEventListener("mouseup", handleMouseUp);
    return () => {
      document.removeEventListener("mousemove", handleMouseMove);
      document.removeEventListener("mouseup", handleMouseUp);
    };
  }, [handleMouseMove, handleMouseUp]);

  useEffect(() => {
    const payload = decoratedParameters.map(({ paramType, ...rest }) => rest);

    try {
      const ev = new CustomEvent(PARAMETERS_UPDATED_EVENT, { detail: payload });
      window.dispatchEvent(ev);
    } catch {
      try {
        const ev = document.createEvent("CustomEvent");
        ev.initCustomEvent(PARAMETERS_UPDATED_EVENT, false, false, payload);
        window.dispatchEvent(ev);
      } catch (err) {
        console.error(
          "ParameterBlock: failed to dispatch parametersUpdated",
          err
        );
      }
    }
  }, [decoratedParameters]);

  const renderParameterItem = useCallback(
    (param) => {
      const originalIndex = parameters.findIndex((p) => p.id === param.id);
      const isEditingLabel =
        editingIndex === originalIndex && editingField === "label";
      const isEditingValue =
        editingIndex === originalIndex && editingField === "value";
      const isData = Boolean(param.isDataParameter);
      const isAutoGenerated = Boolean(param.isAutoGenerated);
      const isSystemSource =
        (param.source || "").toLowerCase() === "system" && !isData;
      const labelEditable = !isData && !isSystemSource;
      const valueEditable = !isAutoGenerated && (isData || !isSystemSource);

      const labelTitle = labelEditable
        ? "Click to edit"
        : isAutoGenerated
        ? "Auto-generated parameter - label locked"
        : isData
        ? "Linked parameter - label editing disabled"
        : "System parameter - label locked";

      const valueTitle = valueEditable
        ? "Click to edit"
        : isAutoGenerated
        ? "Auto-generated parameter"
        : "System parameter - value locked";

      return (
        <li
          key={param.id}
          className={`parameter-item ${param.paramType.color} ${
            isData ? "data-parameter" : ""
          }`}
        >
          <span className="parameter-label">
            <span className={`parameter-icon ${param.paramType.color}`}>
              {param.paramType.icon}
            </span>
            {isEditingLabel ? (
              <input
                className="parameter-text-input"
                type="text"
                value={tempValue}
                onChange={(e) => setTempValue(e.target.value)}
                onBlur={saveEdit}
                onKeyDown={handleKeyPress}
                onFocus={() => setTempValue("")}
                autoFocus
              />
            ) : (
              <span
                className="parameter-label-content"
                draggable
                onClick={() =>
                  labelEditable &&
                  startEditing(originalIndex, "label", param.label)
                }
                onDragStart={(event) => {
                  event.dataTransfer.setData(
                    "application/reactflow",
                    JSON.stringify(buildDragPayload(param))
                  );
                }}
                style={{ cursor: labelEditable ? "pointer" : "default" }}
                title={labelTitle}
              >
                {param.label}
              </span>
            )}
          </span>
          <span className="parameter-value">
            {!valueEditable ? (
              <span className="parameter-value-readonly" title={valueTitle}>
                {normalizeValue(param.value) || "[Auto-generated]"}
              </span>
            ) : isEditingValue ? (
              <input
                className="parameter-number-input"
                type="text"
                placeholder="e.g. entry, entry * 0.95"
                value={tempValue}
                onChange={(e) => setTempValue(e.target.value)}
                onBlur={saveEdit}
                onKeyDown={handleKeyPress}
                autoFocus
              />
            ) : (
              <span
                onClick={() =>
                  startEditing(originalIndex, "value", param.value)
                }
                style={{ cursor: "pointer", marginRight: "8px" }}
                title={valueTitle}
              >
                {normalizeValue(param.value) || "—"}
              </span>
            )}
            {/*<button
              onClick={() => handleDeleteClick(originalIndex)}
              className="remove-btn"
              disabled={isAutoGenerated}
              aria-disabled={isAutoGenerated}
            >
              ×
            </button>*/}
          </span>
        </li>
      );
    },
    [
      parameters,
      editingIndex,
      editingField,
      tempValue,
      saveEdit,
      handleKeyPress,
      startEditing,
      /*handleDeleteClick,*/
    ]
  );

  return (
    <div
      ref={parameterBlockRef}
      className={`parameters-dropdown ${
        dropdownState ? "expanded" : "collapsed"
      } ${!hasMatchingParameters ? "empty" : ""} ${
        isDragging ? "dragging" : ""
      }`}
      style={{
        transform: `translateX(${currentX}px)`,
        position: "absolute",
        left: 0,
        top: 0,
        zIndex: 1000,
      }}
    >
      <h1
        className="dropdown-title"
        onClick={onClickDropdownButton}
        onMouseDown={handleMouseDown}
      >
        Parameter Dashboard
        <span className="toggle-icon" onClick={onClickToggleIcon}>
          {dropdownState ? "▲" : "▼"}
        </span>
      </h1>
      <div className="dropdown-content">
        <div className="parameter-controls">
          <div className="search-container">
            <input
              type="text"
              placeholder="Search parameters..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="parameter-search"
            />
          </div>

          <div className="buttons">
            <button
              className="add-parameter-btn"
              onClick={() => onShowModal("parameter")}
            >
              Add Parameter
            </button>
          </div>
        </div>

        <div className="parameters-list">
          {!hasMatchingParameters ? (
            <div className="empty-state">
              <p>
                {searchTerm
                  ? "No parameters match your search"
                  : "No parameters found"}
              </p>
              <p>
                {searchTerm
                  ? "Try a different search term"
                  : "Use the buttons above to add parameters"}
              </p>
            </div>
          ) : (
            <div className="parameter-groups">
              {["data", "manual"].map((group) => {
                const params = filteredGroupedParameters[group] || [];
                if (!params.length) return null;

                const groupConfig = {
                  data: {
                    title: "Relational Parameters",
                    className: "data",
                  },
                  manual: {
                    title: "Parameters",
                    className: "manual",
                  },
                }[group];

                const collapsed = Boolean(collapsedGroups[group]);

                return (
                  <div className="parameter-group" key={group}>
                    <div
                      className={`group-header ${groupConfig.className}`}
                      onClick={() => toggleGroup(group)}
                    >
                      <span className="group-title">{groupConfig.title}</span>
                      <span className="group-count">({params.length})</span>
                      <span className="group-toggle">
                        {collapsed ? "▼" : "▲"}
                      </span>
                    </div>
                    {!collapsed && (
                      <ul className="group-parameters">
                        {params.map(renderParameterItem)}
                      </ul>
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

ParameterBlock.propTypes = {
  parameters: PropTypes.arrayOf(
    PropTypes.shape({
      id: PropTypes.string.isRequired,
      label: PropTypes.string.isRequired,
      value: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
      family: PropTypes.string,
      source: PropTypes.string,
      isDataParameter: PropTypes.bool,
      isAutoGenerated: PropTypes.bool,
    })
  ).isRequired,
  setParameters: PropTypes.func.isRequired,
  onShowModal: PropTypes.func.isRequired,
  onShowDeleteModal: PropTypes.func.isRequired,
};
