import { useState, useCallback, useMemo, useEffect, useRef } from "react";
import { useReactFlow } from "@xyflow/react";
import "./ParameterBlock.scss";
import PropTypes from "prop-types";
import { useAsset } from "../AssetContext";
import {
  DEFAULT_ASSET,
  DEFAULT_DATA_RESOLUTION,
  DEFAULT_FEE_PERCENT,
  DEFAULT_INTERVAL_BY_RESOLUTION,
} from "../defaults";

const PARAMETERS_UPDATED_EVENT = "parametersUpdated";
const SYSTEM_COLOR_VARIANTS = [
  "system-variant-1",
  "system-variant-2",
  "system-variant-3",
];
const normalizeValue = (value) => {
  if (value === null || value === undefined) {
    return "";
  }
  return typeof value === "string" ? value : String(value);
};

const buildDragPayload = (param) => ({
  label: param.label,
  value: param.value,
  family: param.isDataParameter ? "variable" : param.family || "variable",
  id: param.id,
  source: param.source || "user",
  isDataParameter: Boolean(param.isDataParameter),
  isAutoGenerated: Boolean(param.isAutoGenerated),
  group: typeof param.group === "string" ? param.group : undefined,
});

const SECTION_CONFIG = {
  system: {
    title: "System Parameters",
    className: "bot-received",
    order: 0,
    defaultGroup: "System",
  },
  variable: {
    title: "Variable Parameters",
    className: "manual",
    order: 1,
    defaultGroup: "Ungrouped",
  },
};

export default function ParameterBlock({
  parameters,
  onShowModal,
  onShowDeleteModal,
  isExpandedByTutorial = null,
  onEditParameter,
}) {
  // State to track which parameter and field is being edited
  const [editingIndex, setEditingIndex] = useState(null);
  const [editingField, setEditingField] = useState(null);
  const [tempValue, setTempValue] = useState("");
  const [dropdownState, setDropdownState] = useState(false);

  // Use external tutorial control if provided, otherwise use internal state
  const isDropdownOpen =
    isExpandedByTutorial !== null ? isExpandedByTutorial : dropdownState;
  const setIsDropdownOpen =
    isExpandedByTutorial !== null ? () => {} : setDropdownState;
  const [searchTerm, setSearchTerm] = useState("");
  const [collapsedGroups, setCollapsedGroups] = useState({});

  // Drag state management
  const [isDragging, setIsDragging] = useState(false);
  const [dragOffset, setDragOffset] = useState(0);
  const [currentX, setCurrentX] = useState(0);
  const [canvasBounds, setCanvasBounds] = useState({ left: 0, right: 0 });
  const [dragStartPos, setDragStartPos] = useState({ x: 0, y: 0 });
  const [hasDragged, setHasDragged] = useState(false);
  const parameterBlockRef = useRef(null);
  const [activeTab, setActiveTab] = useState("parameters");

  const classifyParameter = useCallback((param) => {
    if (param.isDataParameter) {
      return { type: "system", color: SYSTEM_COLOR_VARIANTS[0], icon: "⬤" };
    }

    const label = normalizeValue(param.label).toLowerCase();
    const source = normalizeValue(param.source).toLowerCase();
    const isSystem = source === "system";

    if (
      isSystem ||
      label.includes("close") ||
      label.includes("close price") ||
      label.includes("live")
    ) {
      return { type: "variable", color: "green", icon: "●" };
    }

    if (isSystem || label.includes("indicator") || label.includes("output")) {
      return { type: "variable", color: "dark-blue", icon: "●" };
    }

    if (isSystem || label.includes("entry")) {
      return { type: "variable", color: "pink", icon: "●" };
    }

    return { type: "variable", color: "default", icon: "○" };
  }, []);

  const decoratedParameters = useMemo(() => {
    let systemColorIndex = 0;

    return parameters.map((param) => {
      const value = normalizeValue(param.value);
      const paramType = classifyParameter(param);
      if (param.isDataParameter) {
        const variant =
          SYSTEM_COLOR_VARIANTS[
            systemColorIndex % SYSTEM_COLOR_VARIANTS.length
          ];
        systemColorIndex += 1;
        paramType.color = variant;
      }
      const rawFamily = normalizeValue(param.family);
      const family = param.isDataParameter
        ? "variable"
        : rawFamily === "relational"
        ? "variable"
        : rawFamily || paramType.type || "variable";
      const group = typeof param.group === "string" ? param.group.trim() : "";
      return {
        ...param,
        value,
        paramType,
        family,
        group,
        isDataParameter: Boolean(param.isDataParameter),
        isAutoGenerated: Boolean(param.isAutoGenerated),
      };
    });
  }, [parameters, classifyParameter]);

  const groupedParameters = useMemo(() => {
    const sections = new Map();
    const ensureSection = (key) => {
      if (!sections.has(key)) {
        const config = SECTION_CONFIG[key] || SECTION_CONFIG.variable;
        sections.set(key, {
          key,
          title: config.title,
          className: config.className,
          defaultGroup: config.defaultGroup,
          order: config.order,
          groups: new Map(),
        });
      }
      return sections.get(key);
    };

    decoratedParameters.forEach((param) => {
      const inferredType = param.paramType?.type;
      const sectionKey = SECTION_CONFIG[inferredType]
        ? inferredType
        : param.isDataParameter
        ? "system"
        : "variable";
      const section = ensureSection(sectionKey);
      const rawGroup =
        param.group && param.group !== "" ? param.group : section.defaultGroup;
      const normalizedGroup = String(rawGroup).toLowerCase();
      if (!section.groups.has(normalizedGroup)) {
        section.groups.set(normalizedGroup, {
          displayName: rawGroup,
          params: [],
        });
      }
      const entry = section.groups.get(normalizedGroup);
      if (!entry.displayName && rawGroup) {
        entry.displayName = rawGroup;
      }
      entry.params.push(param);
    });

    const entries = [];
    sections.forEach((section) => {
      section.groups.forEach((groupEntry, groupKey) => {
        entries.push({
          key: `${section.key}::${groupKey}`,
          sectionKey: section.key,
          title: section.title,
          className: section.className,
          groupName: groupEntry.displayName || section.defaultGroup,
          params: groupEntry.params,
          order: section.order,
        });
      });
    });

    entries.sort((a, b) => {
      if (a.order !== b.order) return a.order - b.order;
      return a.groupName.localeCompare(b.groupName);
    });

    return entries;
  }, [decoratedParameters]);

  const filteredGroupedParameters = useMemo(() => {
    if (searchTerm === "") {
      return groupedParameters;
    }

    const term = searchTerm.toLowerCase();
    const matches = (param) =>
      param.label.toLowerCase().includes(term) ||
      normalizeValue(param.value).toLowerCase().includes(term) ||
      (param.group || "").toLowerCase().includes(term);

    return groupedParameters
      .map((entry) => {
        const matchesGroup = entry.groupName
          ? entry.groupName.toLowerCase().includes(term)
          : false;
        const params = matchesGroup
          ? entry.params
          : entry.params.filter(matches);
        return {
          ...entry,
          params,
        };
      })
      .filter((entry) => entry.params.length > 0);
  }, [groupedParameters, searchTerm]);

  const hasMatchingParameters = filteredGroupedParameters.length > 0;

  const startEditing = useCallback(
    (index, field, currentValue) => {
      const target = parameters[index];
      if (!target) {
        return;
      }
      if (target.isAutoGenerated) {
        return;
      }
      if (target?.isDataParameter && field !== "value") {
        return;
      }
      setEditingIndex(index);
      setEditingField(field);
      setTempValue(currentValue);
    },
    [parameters]
  );

  const saveEdit = useCallback(() => {
    if (editingIndex === null || !editingField) {
      setEditingIndex(null);
      setEditingField(null);
      setTempValue("");
      return;
    }

    const target = parameters[editingIndex];
    if (!target || target.isAutoGenerated) {
      setEditingIndex(null);
      setEditingField(null);
      setTempValue("");
      return;
    }

    if (target?.isDataParameter && editingField === "label") {
      setEditingIndex(null);
      setEditingField(null);
      setTempValue("");
      return;
    }

    const trimmedValue = tempValue.trim();
    const requiresValue = editingField === "label" || editingField === "value";

    if (requiresValue && !trimmedValue) {
      setEditingIndex(null);
      setEditingField(null);
      setTempValue("");
      return;
    }

    // setParameters((prev) =>
    //   prev.map((param, index) => {
    //     if (index !== editingIndex) {
    //       return param;
    //     }

    //     if (editingField === "group") {
    //       if (trimmedValue) {
    //         return { ...param, group: trimmedValue };
    //       }
    //       const { group, ...rest } = param;
    //       return rest;
    //     }

    //     return { ...param, [editingField]: trimmedValue };
    //   })
    // );

    if (typeof onEditParameter === "function") {
      const valueToPersist = trimmedValue;
      onEditParameter(target.id, editingField, valueToPersist);
    }

    setEditingIndex(null);
    setEditingField(null);
    setTempValue("");
  }, [editingIndex, editingField, tempValue, parameters, onEditParameter]);

  const cancelEdit = useCallback(() => {
    setEditingIndex(null);
    setEditingField(null);
    setTempValue("");
  }, []);

  const handleKeyPress = useCallback(
    (e) => {
      if (e.key === "Enter") {
        saveEdit();
      } else if (e.key === "Escape") {
        cancelEdit();
      }
    },
    [saveEdit, cancelEdit]
  );

  const onClickDropdownButton = useCallback(() => {
    if (hasDragged) {
      return;
    }
    // Only allow toggling if not controlled by tutorial
    if (isExpandedByTutorial === null) {
      setDropdownState((prev) => !prev);
    }
  }, [hasDragged, isExpandedByTutorial]);

  const onClickToggleIcon = useCallback(
    (e) => {
      e.stopPropagation();
      // Only allow toggling if not controlled by tutorial
      if (isExpandedByTutorial === null) {
        setDropdownState((prev) => !prev);
      }
    },
    [isExpandedByTutorial]
  );

  // eslint-disable-next-line no-unused-vars
  const handleDeleteClick = useCallback(
    (index) => {
      const target = parameters[index];
      if (target?.isAutoGenerated) {
        return;
      }
      onShowDeleteModal(index);
    },

    [onShowDeleteModal, parameters]
  );

  const toggleGroup = useCallback((groupId) => {
    setCollapsedGroups((prev) => ({
      ...prev,
      [groupId]: !prev[groupId],
    }));
  }, []);

  useEffect(() => {
    const updateCanvasBounds = () => {
      if (parameterBlockRef.current) {
        const canvas = parameterBlockRef.current.closest(".react-flow");
        if (canvas) {
          const rect = canvas.getBoundingClientRect();
          const blockWidth = parameterBlockRef.current.offsetWidth;
          setCanvasBounds({
            left: 0,
            right: rect.width - blockWidth,
          });
        }
      }
    };

    updateCanvasBounds();
    window.addEventListener("resize", updateCanvasBounds);
    return () => window.removeEventListener("resize", updateCanvasBounds);
  }, []);

  const handleMouseDown = useCallback((e) => {
    if (
      e.target.closest(".dropdown-title") &&
      !e.target.closest(".toggle-icon")
    ) {
      setDragStartPos({ x: e.clientX, y: e.clientY });
      setHasDragged(false);
      const rect = parameterBlockRef.current.getBoundingClientRect();
      setDragOffset(e.clientX - rect.left);
    }
  }, []);

  const handleMouseMove = useCallback(
    (e) => {
      if (dragStartPos.x !== 0 && dragStartPos.y !== 0) {
        const deltaX = Math.abs(e.clientX - dragStartPos.x);
        const deltaY = Math.abs(e.clientY - dragStartPos.y);

        if (deltaX > 5 && deltaX > deltaY) {
          if (!isDragging) {
            setIsDragging(true);
            setHasDragged(true);
            document.body.style.cursor = "grabbing";
            document.body.style.userSelect = "none";
          }

          const newX = e.clientX - dragOffset;
          const constrainedX = Math.max(
            canvasBounds.left,
            Math.min(canvasBounds.right, newX)
          );
          setCurrentX(constrainedX);
        }
      }
    },
    [dragStartPos, dragOffset, canvasBounds, isDragging]
  );

  const handleMouseUp = useCallback(() => {
    if (isDragging) {
      setIsDragging(false);
      document.body.style.cursor = "";
      document.body.style.userSelect = "";
    }
    setDragStartPos({ x: 0, y: 0 });
  }, [isDragging]);

  useEffect(() => {
    document.addEventListener("mousemove", handleMouseMove);
    document.addEventListener("mouseup", handleMouseUp);
    return () => {
      document.removeEventListener("mousemove", handleMouseMove);
      document.removeEventListener("mouseup", handleMouseUp);
    };
  }, [handleMouseMove, handleMouseUp]);

  useEffect(() => {
    const payload = decoratedParameters.map(({ paramType, ...rest }) => rest);

    try {
      const ev = new CustomEvent(PARAMETERS_UPDATED_EVENT, { detail: payload });
      window.dispatchEvent(ev);
    } catch {
      try {
        const ev = document.createEvent("CustomEvent");
        ev.initCustomEvent(PARAMETERS_UPDATED_EVENT, false, false, payload);
        window.dispatchEvent(ev);
      } catch (err) {
        console.error(
          "ParameterBlock: failed to dispatch parametersUpdated",
          err
        );
      }
    }
  }, [decoratedParameters]);

  const renderParameterItem = useCallback(
    (param) => {
      const originalIndex = parameters.findIndex((p) => p.id === param.id);
      const isEditingLabel =
        editingIndex === originalIndex && editingField === "label";
      const isEditingValue =
        editingIndex === originalIndex && editingField === "value";
      const isData = Boolean(param.isDataParameter);
      const isAutoGenerated = Boolean(param.isAutoGenerated);
      const isSystemSource =
        (param.source || "").toLowerCase() === "system" && !isData;
      const labelEditable = !isData && !isSystemSource;
      const valueEditable = !isAutoGenerated && (isData || !isSystemSource);
      const labelTitle = labelEditable
        ? "Click to edit"
        : isAutoGenerated
        ? "Auto-generated parameter - label locked"
        : isData
        ? "Linked parameter - label editing disabled"
        : "System parameter - label locked";

      const valueTitle = valueEditable
        ? "Click to edit"
        : isAutoGenerated
        ? "Auto-generated parameter"
        : "System parameter - value locked";

      return (
        <li
          key={param.id}
          className={`parameter-item ${param.paramType.color} ${
            isData ? "data-parameter" : ""
          }`}
        >
          <span className="parameter-label">
            <span className={`parameter-icon ${param.paramType.color}`}>
              {param.paramType.icon}
            </span>
            {isEditingLabel ? (
              <input
                className="parameter-text-input"
                type="text"
                value={tempValue}
                onChange={(e) => setTempValue(e.target.value)}
                onBlur={saveEdit}
                onKeyDown={handleKeyPress}
                onFocus={() => setTempValue("")}
                autoFocus
              />
            ) : (
              <span
                className="parameter-label-content"
                draggable
                onClick={() =>
                  labelEditable &&
                  startEditing(originalIndex, "label", param.label)
                }
                onDragStart={(event) => {
                  event.dataTransfer.setData(
                    "application/reactflow",
                    JSON.stringify(buildDragPayload(param))
                  );
                }}
                style={{ cursor: labelEditable ? "pointer" : "default" }}
                title={labelTitle}
              >
                {param.label}
              </span>
            )}
          </span>
          <span className="parameter-value">
            {!valueEditable ? (
              <span className="parameter-value-readonly" title={valueTitle}>
                {normalizeValue(param.value) || "[Auto-generated]"}
              </span>
            ) : isEditingValue ? (
              <input
                className="parameter-number-input"
                type="text"
                placeholder="e.g. entry, entry * 0.95"
                value={tempValue}
                onChange={(e) => setTempValue(e.target.value)}
                onBlur={saveEdit}
                onKeyDown={handleKeyPress}
                autoFocus
              />
            ) : (
              <span
                className="parameter-value-editable"
                onClick={() =>
                  startEditing(originalIndex, "value", param.value)
                }
                style={{ cursor: "pointer" }}
                title={valueTitle}
              >
                {normalizeValue(param.value) || "—"}
              </span>
            )}

            {/*<button
              onClick={() => handleDeleteClick(originalIndex)}
              className="remove-btn"
              disabled={isAutoGenerated}
              aria-disabled={isAutoGenerated}
            >
              ×
            </button>*/}
          </span>
        </li>
      );
    },
    [
      parameters,
      editingIndex,
      editingField,
      tempValue,
      saveEdit,
      handleKeyPress,
      startEditing,
      /*handleDeleteClick,*/
    ]
  );

  return (
    <div
      ref={parameterBlockRef}
      className={`parameters-dropdown ${
        dropdownState ? "expanded" : "collapsed"
      } ${!hasMatchingParameters ? "empty" : ""} ${
        isDragging ? "dragging" : ""
      }`}
      style={{
        transform: `translateX(${currentX}px)`,
        position: "absolute",
        left: 0,
        top: 0,
        zIndex: 1000,
      }}
    >
      <h1
        className="dropdown-title"
        onClick={onClickDropdownButton}
        onMouseDown={handleMouseDown}
      >
        Parameter Dashboard
        <span className="toggle-icon" onClick={onClickToggleIcon}>
          {dropdownState ? "▲" : "▼"}
        </span>
      </h1>
      <div className="dropdown-content">
        <div className="parameter-tabs">
          <button
            type="button"
            className={activeTab === "parameters" ? "active" : ""}
            onClick={() => setActiveTab("parameters")}
          >
            Parameters
          </button>
          <button
            type="button"
            className={activeTab === "dataset" ? "active" : ""}
            onClick={() => setActiveTab("dataset")}
          >
            Back-Test Data Set
          </button>
        </div>

        {activeTab === "parameters" ? (
          <>
            <div className="parameter-controls">
              <div className="search-container">
                <input
                  type="text"
                  placeholder="Search parameters..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="parameter-search"
                />
              </div>

              <div className="buttons">
                <button
                  className="add-parameter-btn"
                  onClick={() => onShowModal()}
                >
                  Add Parameter
                </button>
              </div>
            </div>

            <div className="parameters-list">
              {!hasMatchingParameters ? (
                <div className="empty-state">
                  <p>
                    {searchTerm
                      ? "No parameters match your search"
                      : "No parameters found"}
                  </p>
                  <p>
                    {searchTerm
                      ? "Try a different search term"
                      : "Use the buttons above to add parameters"}
                  </p>
                </div>
              ) : (
                <div className="parameter-groups">
                  {filteredGroupedParameters.map((group) => {
                    const collapsed = Boolean(collapsedGroups[group.key]);
                    return (
                      <div className="parameter-group" key={group.key}>
                        <div
                          className={`group-header ${group.className}`}
                          onClick={() => toggleGroup(group.key)}
                        >
                          <span className="group-title">{group.title}</span>
                          <span className="group-count">
                            ({group.params.length})
                          </span>
                          <span className="group-toggle">
                            {collapsed ? "▼" : "▲"}
                          </span>
                        </div>
                        {!collapsed && (
                          <ul className="group-parameters">
                            {group.params.map(renderParameterItem)}
                          </ul>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          </>
        ) : (
          <BacktestDatasetTab />
        )}
      </div>
    </div>
  );
}

ParameterBlock.propTypes = {
  parameters: PropTypes.arrayOf(
    PropTypes.shape({
      id: PropTypes.string.isRequired,
      label: PropTypes.string.isRequired,
      value: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
      family: PropTypes.string,
      source: PropTypes.string,
      group: PropTypes.string,
      isDataParameter: PropTypes.bool,
      isAutoGenerated: PropTypes.bool,
    })
  ).isRequired,
  onShowModal: PropTypes.func.isRequired,
  onShowDeleteModal: PropTypes.func.isRequired,
  onEditParameter: PropTypes.func,
};

function BacktestDatasetTab() {
  const reactFlow = useReactFlow();
  const assetContext = useAsset();
  const inputNode = reactFlow?.getNode?.("inputNode") || null;
  const data = inputNode?.data || {};
  const RESOLUTION_LIMITS = useMemo(
    () => ({
      "1d": { min: 1, max: 365, unit: "days" },
      "1h": { min: 1, max: 8760, unit: "hours" },
    }),
    []
  );
  const resolution = data.resolution || DEFAULT_DATA_RESOLUTION;
  const intervalBounds =
    RESOLUTION_LIMITS[resolution] || RESOLUTION_LIMITS["1d"];
  const defaultInterval = String(
    data.interval ??
      DEFAULT_INTERVAL_BY_RESOLUTION[resolution] ??
      intervalBounds.min
  );
  const defaultFee = String(
    data.feePercent ??
      data.feePercentage ??
      assetContext.feePercent ??
      DEFAULT_FEE_PERCENT
  );

  const [formState, setFormState] = useState({
    asset: data.asset || DEFAULT_ASSET,
    interval: defaultInterval,
    fee: defaultFee,
  });
  const [dirty, setDirty] = useState({
    asset: false,
    interval: false,
    fee: false,
  });
  const [flashing, setFlashing] = useState({});

  useEffect(() => {
    if (!inputNode) return;
    const nodeData = inputNode.data || {};
    const nodeResolution = nodeData.resolution || DEFAULT_DATA_RESOLUTION;
    const bounds = RESOLUTION_LIMITS[nodeResolution] || RESOLUTION_LIMITS["1d"];
    const syncedInterval = String(
      nodeData.interval ??
        DEFAULT_INTERVAL_BY_RESOLUTION[nodeResolution] ??
        bounds.min
    );
    const syncedFee = String(
      nodeData.feePercent ??
        nodeData.feePercentage ??
        assetContext.feePercent ??
        DEFAULT_FEE_PERCENT
    );

    setFormState((prev) => ({
      asset: dirty.asset ? prev.asset : nodeData.asset || DEFAULT_ASSET,
      interval: dirty.interval ? prev.interval : syncedInterval,
      fee: dirty.fee ? prev.fee : syncedFee,
    }));
  }, [
    inputNode,
    data.asset,
    data.interval,
    data.feePercent,
    data.feePercentage,
    data.resolution,
    assetContext.feePercent,
    dirty.asset,
    dirty.interval,
    dirty.fee,
    RESOLUTION_LIMITS,
  ]);

  const flashField = useCallback((field) => {
    setFlashing((prev) => ({ ...prev, [field]: true }));
    setTimeout(() => setFlashing((prev) => ({ ...prev, [field]: false })), 600);
  }, []);

  const commitChanges = useCallback(
    (patch) => {
      if (!inputNode) return;
      reactFlow.updateNodeData(inputNode.id, {
        ...inputNode.data,
        ...patch,
      });
    },
    [inputNode, reactFlow]
  );

  const handleAssetChange = (value) => {
    if (!value || value === formState.asset) return;
    setDirty((prev) => ({ ...prev, asset: true }));
    setFormState((prev) => ({ ...prev, asset: value }));
    assetContext.setSelectedAsset(value);
    commitChanges({ asset: value });
    setDirty((prev) => ({ ...prev, asset: false }));
    flashField("asset");
  };

  const handleIntervalChange = (value) => {
    const cleaned = value.replace(/[^0-9-]/g, "").replace(/(?!^)-/g, "");
    setDirty((prev) => ({ ...prev, interval: true }));
    setFormState((prev) => ({ ...prev, interval: cleaned }));
  };

  const handleIntervalBlur = () => {
    const numeric = Number(formState.interval);
    const clamped =
      Number.isFinite(numeric) && numeric > 0
        ? Math.min(Math.max(numeric, intervalBounds.min), intervalBounds.max)
        : intervalBounds.min;
    const clampedStr = String(clamped);
    if (clampedStr !== formState.interval) {
      setFormState((prev) => ({ ...prev, interval: clampedStr }));
    }
    commitChanges({ interval: clamped });
    assetContext.setHistoryWindow(clamped);
    setDirty((prev) => ({ ...prev, interval: false }));
    flashField("interval");
  };

  const handleFeeChange = (value) => {
    const cleaned = value.replace(/[^0-9.-]/g, "");
    setDirty((prev) => ({ ...prev, fee: true }));
    setFormState((prev) => ({ ...prev, fee: cleaned }));
  };

  const handleFeeBlur = () => {
    const numeric = Number(formState.fee);
    const feeValue = Number.isFinite(numeric) ? numeric : DEFAULT_FEE_PERCENT;
    const feeStr = String(feeValue);
    if (feeStr !== formState.fee) {
      setFormState((prev) => ({ ...prev, fee: feeStr }));
    }
    commitChanges({ feePercent: feeValue });
    assetContext.setFeePercent(feeValue);
    setDirty((prev) => ({ ...prev, fee: false }));
    flashField("fee");
  };

  return (
    <div className="dataset-tab">
      {!inputNode ? (
        <div className="dataset-empty">Back-test node not found.</div>
      ) : (
        <div className="dataset-form">
          <div className={`dataset-field ${flashing.asset ? "flash" : ""}`}>
            <label htmlFor="dataset-asset">Asset</label>
            <select
              id="dataset-asset"
              value={formState.asset}
              onChange={(e) => handleAssetChange(e.target.value)}
            >
              <option value="bitcoin">BTC</option>
              <option value="ethereum">ETH</option>
            </select>
          </div>

          <div className="dataset-field locked">
            <label htmlFor="dataset-resolution">Data Resolution</label>
            <div className="field-control field-control--locked">
              <select id="dataset-resolution" value={resolution} disabled>
                <option value="1d">1 Day</option>
                <option value="1h">1 Hour</option>
              </select>
              <span className="field-lock" aria-hidden="true" title="Locked">
                <svg
                  viewBox="0 0 16 16"
                  xmlns="http://www.w3.org/2000/svg"
                  focusable="false"
                >
                  <rect x="3.25" y="7.25" width="9.5" height="7.5" rx="1.5" />
                  <path d="M11 7V5a3 3 0 0 0-6 0v2" />
                  <circle cx="8" cy="10.5" r="0.85" />
                </svg>
              </span>
            </div>
          </div>

          <div className={`dataset-field ${flashing.interval ? "flash" : ""}`}>
            <label htmlFor="dataset-history">History Window</label>
            <div className="dataset-history-input">
              <input
                id="dataset-history"
                type="text"
                value={formState.interval}
                onChange={(e) => handleIntervalChange(e.target.value)}
                onBlur={handleIntervalBlur}
              />
              <span>{intervalBounds.unit}</span>
            </div>
          </div>

          <div className="dataset-field locked">
            <label htmlFor="dataset-type">Type</label>
            <div className="field-control field-control--locked">
              <select
                id="dataset-type"
                value={data.type || "realtime"}
                disabled
              >
                <option value="realtime">Real-Time</option>
                <option value="batch">Batch</option>
                <option value="stream">Stream</option>
              </select>
              <span className="field-lock" aria-hidden="true" title="Locked">
                <svg
                  viewBox="0 0 16 16"
                  xmlns="http://www.w3.org/2000/svg"
                  focusable="false"
                >
                  <rect x="3.25" y="7.25" width="9.5" height="7.5" rx="1.5" />
                  <path d="M11 7V5a3 3 0 0 0-6 0v2" />
                  <circle cx="8" cy="10.5" r="0.85" />
                </svg>
              </span>
            </div>
          </div>

          <div className={`dataset-field ${flashing.fee ? "flash" : ""}`}>
            <label htmlFor="dataset-fee">Fee Percentage</label>
            <div className="dataset-fee-input">
              <input
                id="dataset-fee"
                type="text"
                value={formState.fee}
                onChange={(e) => handleFeeChange(e.target.value)}
                onBlur={handleFeeBlur}
              />
              <span>%</span>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
