import "./setParameter.scss";
import NodeDefault from "../nodeDefault";
import PropTypes from "prop-types";
import { useState, useEffect, useMemo, useRef } from "react";
import { useReactFlow } from "@xyflow/react";

const DEFAULT_LABEL = "parameter";
const DEFAULT_SOURCE = "system";

const resolveLabel = (nodeData) => {
  if (!nodeData) return DEFAULT_LABEL;
  const candidates = [
    nodeData.parameterLabel,
    nodeData.parameterName,
    nodeData.parameterData?.label,
  ];

  for (const candidate of candidates) {
    if (typeof candidate === "string" && candidate.trim()) {
      return candidate.trim();
    }
  }

  return DEFAULT_LABEL;
};

const resolveValue = (nodeData, fallbackLabel) => {
  if (!nodeData) return fallbackLabel;
  const raw = nodeData.parameterData?.value;
  if (typeof raw === "string" && raw.trim()) {
    return raw.trim();
  }
  return fallbackLabel;
};

const resolveSource = (nodeData) => {
  const raw = nodeData?.parameterData?.source;
  if (typeof raw === "string" && raw.trim()) {
    return raw.trim();
  }
  return DEFAULT_SOURCE;
};

export default function SetParameter({ data, id }) {
  const { updateNodeData } = useReactFlow();

  const parameterIdRef = useRef(
    data?.parameterId ||
      data?.parameterData?.parameterId ||
      `set-parameter-${id || Date.now()}`
  );
  const parameterId = parameterIdRef.current;

  const initialLabel = useMemo(() => resolveLabel(data), [data]);
  const [label, setLabel] = useState(initialLabel);
  const [value, setValue] = useState(() => resolveValue(data, initialLabel));

  const source = useMemo(() => resolveSource(data), [data]);

  useEffect(() => {
    const nextLabel = resolveLabel(data);
    if (nextLabel !== label) {
      setLabel(nextLabel);
    }

    const nextValue = resolveValue(data, nextLabel);
    if (nextValue !== value) {
      setValue(nextValue);
    }
  }, [data, label, value]);

  const parameterData = useMemo(
    () => ({
      parameterId,
      label,
      value,
      source,
      isDataParameter: true,
      isAutoGenerated: true,
    }),
    [label, parameterId, source, value]
  );

  useEffect(() => {
    const existing = data || {};
    const needsUpdate =
      existing.parameterId !== parameterId ||
      existing.parameterName !== label ||
      existing.parameterLabel !== label ||
      !existing.parameterData ||
      existing.parameterData.label !== label ||
      existing.parameterData.value !== value ||
      (existing.parameterData.source || DEFAULT_SOURCE) !== source;

    if (!id || !needsUpdate) return;

    const {
      parameterId: _ignoredId,
      parameterName: _ignoredName,
      parameterLabel: _ignoredLabel,
      parameterData: _ignoredData,
      ...rest
    } = existing;

    updateNodeData(id, {
      ...rest,
      parameterId,
      parameterName: label,
      parameterLabel: label,
      parameterData,
    });
  }, [
    data,
    id,
    label,
    parameterData,
    parameterId,
    source,
    updateNodeData,
    value,
  ]);

  useEffect(() => {
    const handleParametersUpdated = (event) => {
      const params = event?.detail || event;
      if (!Array.isArray(params)) return;

      const match = params.find((param) => param.id === parameterId);
      if (!match) return;

      if (typeof match.label === "string") {
        const nextLabel = match.label.trim() || DEFAULT_LABEL;
        if (nextLabel !== label) {
          setLabel(nextLabel);
        }
      }

      if (typeof match.value === "string") {
        const nextValue = match.value.trim() || label;
        if (nextValue !== value) {
          setValue(nextValue);
        }
      }
    };

    window.addEventListener("parametersUpdated", handleParametersUpdated);
    return () => {
      window.removeEventListener("parametersUpdated", handleParametersUpdated);
    };
  }, [label, parameterId, value]);

  return (
    <NodeDefault
      id={id}
      title="Set Parameter"
      left={{ active: true, type: "target" }}
    >
      <div className="set-parameter-node">
        <span className="set-parameter-chip">{label}</span>
      </div>
    </NodeDefault>
  );
}

SetParameter.propTypes = {
  id: PropTypes.string,
  data: PropTypes.object,
};
